### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by leifliddy** [amworsley/asahi-wiki#1]
I just got a macbook air M1 today and am just trying to boot Linux on it in any sort of form or fashion.
But the documentation is all over the place. 
Your ```config-wifi3``` really helped me out. That got the keyboard working for me with the ```asahi``` and the ```wifi/take5``` branches. 

To be honest I'm at a knowledge deficit here. Ideally I'd like to install Fedora, but right now any distro will do (as I'm currently in the learning phase of how this all works).

I've tried direct loading that debian ```initrd.gz``` with 
```sudo python ~/git.projects/m1n1/proxyclient/tools/linux.py -b 'earlycon console=ttySAC0,1500000 console=tty0 debug' Image.gz t8103-j313.dtb initrd.gz```

But receive an error during the install process due to kernel module mismatches --which makes sense as that initrd contains modules from a different kernel version. 
I would just like to know how to create an ```initrd.gz``` (for any distro) that would allow me to install Linux on this Macbook. 
Could you please share with me how how you created that file?
Once I get these steps down I'm going to create clear and concise guide on how to install Linux on the Macbook Air M1.

**Comment by amworsley** [comment]
I would strongly recommend looking at [Glanzmann's guide](https://tg.st/u/asahi.txt) which goes through the debian install set up.

To get around the module issue - you can build everything into the kernel, there
are some WiFi dongle's that only build as modulees but if you install the firmware
into your rootfs you can get the inbuilt wifi to work.
Change a ll the =m to =y in the .config

To get another rootfs (e.g. on a USB drive) arm64 rootfs you can take debstrap way
or take a raspberry pi (one with 64bit CPU). Once you have you can format the nvme partition should set aside as ext4 and cp the root filesystem onto it.

Once I got that  booted  as my rootfs (root=/dev/nvme0n1p4 rootwait rootfstype=ext4) or what ever partition you get (as per Glanzmann's notes) I installed the compiler, git and built asahi kernel and installed with any modules as per:


```
make 
sudo make install modules_install
```

which is quite fast on the mba - about 3.5 minutes I think from memory.
Marcan is promising that this will soon be much easier when get's to work on
automating much of this.

Note please hang out on the IRC where I learnt most stuff from others.


Andrew

**Comment by leifliddy** [comment]
![Screenshot from 2021-12-28 23-21-14](https://user-images.githubusercontent.com/12903289/147611371-fdcf7783-5791-4252-b289-3727402a9a62.png)

\>or take a raspberry pi (one with 64bit CPU).
...or you could use qemu to emulate an aarch64 system ;  )
I really appreciate your response! I have a much better understanding  of how this is meant to work. I really like the concept of dd'ing a root image directly to a partition --because after that all you need is a kernel to boot it.  Or you could just include the kernel inside the rootfs image....so many possibilities. 
I have a few different ideas I'd like to try out and see which one works best.  
The end-goal is to get a Linux system booted and to automate the entire process as much as possible.  
Thanks man...

**Comment by amworsley** [comment]
That's wonderful to hear. It's a great feeling to work out your own unique way.
That's one of the things I love about marcan's work is he is building tools anyone
can pick up use to do more fun and useful things with the hardware!

Andrew

**Comment by leifliddy** [comment]
![20211229_075036](https://user-images.githubusercontent.com/12903289/147649674-311e471b-4e5a-4947-9ea2-522b1e4a91ab.jpg)

My partition table looks like this, I just followed the directions here 
https://github.com/AsahiLinux/docs/wiki/Developer-Quickstart

Looking at Glanzmann's guide I wasn't exactly sure where to dd the rootfs to --as his setup seems to be a bit different. I'm not a "mac person" at all --and I really need to to understand these diskutil commands and how partitions work in macos. Anyways...I ended up bricking this thing (it's a long story) and am in the process of reviving it now. Will try again later today. BTW, what does your ```diskutil list``` output look like?

**Comment by leifliddy** [comment]
Have you heard of this tool before? I just discovered it, testing it out now...
https://0pointer.net/blog/mkosi-a-tool-for-generating-os-images.html
https://wiki.archlinux.org/title/mkosi

**Comment by leifliddy** [comment]
I should have read the directions more closely, ok I see that 
```diskutil addPartition disk0s5 FAT32 LB 1GB``` corresponds to ```Linux / (ext4)```
according to the layout suggested in the guide. Yeah, so that partition definitely needs to be increased -- was probably written before nvme was supported. Ok, I think I'm good now...

But please check out that ```mkosi``` tool  though https://github.com/systemd/mkosi
It might be a more useful for the general Linux community then ```debootstrap``` as it supports more platforms.
Although...it doesn't look like it support different architectures...damn

**Comment by leifliddy** [comment]
![20211229_222828](https://user-images.githubusercontent.com/12903289/147704859-be1d428c-8983-4123-8fea-96b3c929457d.jpg)
Made a ton or progress today. Took me hours to figure some things out. Your posts really helped me out a lot! Unfortunately my desktop isn't showing me the double Hi-DPI option, so everything is super small. It might have something to do with the fact that the desktop is software rendered, I'm not sure. I need to find a solution for that. Anyways, I'm at a point where I can start testing things out, documenting, automating...etc. Feels good to have made it this far. Alright man I'll you leave you alone....thanks again.

**Comment by leifliddy** [comment]
Took me some time, but I finally got this thing down. Created an mkosi-based image builder to create a minimal Fedora image for the M1. 
https://github.com/leifliddy/asahi-fedora-builder
